import Head from "next/head";
import { useQuery } from "urql";
import { PRODUCT_QUERY } from "@/lib/query";
import Product from "@/components/products";
import { Gallery } from "@/styles/Gallery";

export default function Home() {
  //Fetch products from strapi
  const [results] = useQuery({ query: PRODUCT_QUERY });
  const { data, fetching, error } = results;

  //Check for the data coming in
  if (fetching) return <p>Loading...</p>;
  if (error) return <p>Oh no...{error.message}</p>;
  const products = data.products.data;

  return (
    <div>
      <Head>
        <title>MycoBiome</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main>
        <Gallery>
          {products.map((product, index) => (
            <Product
              key={product.attributes.slug}
              product={product}
              index={index}
            />
          ))}
        </Gallery>
      </main>
    </div>
  );
}
